# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  target:  # id of input
    description: 'target to scan'
    required: true
    default: '.'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
#    - ${{ inputs.who-to-greet }}
    - ${{ inputs.target }}
branding:
  icon: 'shield'
  color: 'blue'
