
name: 'SCV'
description: 'Smart Contract Vulnerability Scanner'
inputs:
  target:  # id of input
    description: 'target to scan'
    required: true
    default: '.'
    type: string
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
#    - ${{ inputs.who-to-greet }}
    - ${{ inputs.target }}
branding:
  icon: 'shield'
  color: 'blue'
